workspace.crc.crcSubmit:FireServer("AVOCADO", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BALLOONY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BALLY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BARBECUESAUCE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BARFBAG", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BASKETBALL", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BATTERY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BELL", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BLACKHOLE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BLENDER", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BLOCKY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BOMBY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BOOK", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BOOMBOX", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BOTTLE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BRACELETY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BUBBLE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("BUG", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("CAKE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("CAMERA", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("CHEESEORB", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("CLIP", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("CLOCK", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("CLOUDY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("COINY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("CRT", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("DAVID", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("DISCY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("DONUT", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("DORA", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("EGGY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("EIGHTBALL", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("ERASER", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("EVILLEAFY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("FANNY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("FIREY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("FIREYJUNIOR", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("FLOWER", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("FOLDY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("FRIES", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("GATY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("GELATIN", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("GOLFBALL", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("GRASSY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("ICECUBE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("INCOMETAXRETURNDOCUMENT", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("LEAFY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("LEEK", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("LEGOBRICK", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("LEWIS", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("LIGHTNING", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("LIY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("LOLLIPOP", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("LOSER", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("MARBLE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("MARKER", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("MATCH", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("NAILY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("NEEDLE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("NICKEL", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("NINEBALL", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("ONIGIRI", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PANFLUTE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PDA", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PEN", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PENCIL", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PIE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PILLOW", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PIN", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PINEAPPLE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PRICETAG", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PROFILY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PUFFBALL", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("PURPLEFACE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("REDBUG", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("REMOTE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("ROBOTFLOWER", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("ROBOTY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("ROCKY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("RUBBERSPATULA", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("RUBY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("RUSTYCOIN", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("SAW", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("SHAMPOO", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("SHOPPINGCART", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("SNOWBALL", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("SPONGY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("STAPY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("STEAMY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("TACO", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("TAPE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("TEARDROP", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("TENNISBALL", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("TREE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("TUNE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("TV", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("VHSY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("WAFFLE", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("WINNER", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("WOODY", false)
wait(0.05)
workspace.crc.crcSubmit:FireServer("YELLOWFACE", false)
wait(0.05)